#!/bin/bash

set -e

if [[ -n "${CDM_DEBUG}" ]]; then
    set -x
fi

function usage() {

    echo -n \
        "Usage: $(basename "$0")
Build the website!
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker run -ti --rm \
            -e CDM_DEBUG=1 \
            -e NODE_VERSION=12.16.2 \
            -e YARN_VERSION=1.22.4 \
            -e RUBY_VERSION=2.6.2 \
            -e PYTHON_VERSION=3.7 \
            -v "$PWD/.:/opt/repo" \
            -v "$PWD/.netlify-cache:/opt/buildhome/cache" \
            -w /opt/build \
            --entrypoint /bin/bash \
            netlify/build:xenial \
            -c "build ./scripts/cibuild && rsync -acvz --delete /opt/buildhome/repo/build/ /opt/repo/build/"
    fi
fi
