#!/bin/bash

set -e

if [[ -n "${CDM_DEBUG}" ]]; then
    set -x
fi

IMAGE_NAME=commonhealth_dashboard_dataproc

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Launch Bash within the Jupyter container image.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it \
        -v $(pwd):/opt/src \
        -v $(pwd)/entrypoint.sh:/opt/entrypoint.sh \
        -e "CHM_GOOGLEAPI_REFRESH_TOKEN=${CHM_GOOGLEAPI_REFRESH_TOKEN}" \
        -e "CHM_GOOGLEAPI_CLIENT_ID=${CHM_GOOGLEAPI_CLIENT_ID}" \
        -e "CHM_GOOGLEAPI_CLIENT_SECRET=${CHM_GOOGLEAPI_CLIENT_SECRET}" \
        ${IMAGE_NAME}:latest \
        /opt/src
fi
